### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Starty06** [LyubomirT/c.ai-addons#11]
This might sound stupid but I'm new and I have no clue on how to download the extension
I'm using a Firefox browser and I have chrome too
When using the developer mode on Firefox the folder doesn't work
Maybe I'm doing something wrong but anyway please help me

**Comment by LyubomirT** [comment]
Hello! Please describe the instructions you followed while installing the extension. Did you unzip the file before installing it? What Firefox version do you use?

**Comment by LyubomirT** [comment]
As a quick/dirty method, you could try opening `manifest.json` file (unpack the `.zip` before proceeding) and replacing `3` in the `manifest_version` field with `2`, since some users have reported that Manifest v3 doesn't work for them in Firefox.

**Comment by LyubomirT** [comment]
@Starty06 Found the issue. It seems like installation steps for Firefox differ from how you would normally install the extension on a typical Chromium-based browser. I'll update the installation instructions in README and provide a Firefox build. Sorry for the inconvenience.

**Comment by LyubomirT** [comment]
@Starty06 Fixed the issue. Please download the `.xpi` file available for Firefox from [here](https://github.com/LyubomirT/c.ai-addons/releases/download/0.5.0/caiaddons-050-mozilla-stable.xpi) (available in the `0.5.0` release). This is a direct link so clicking on it will immediately download the file for you.

After downloading, please take a look at [Firefox Installation Instructions](https://github.com/LyubomirT/c.ai-addons/tree/main?tab=readme-ov-file#installation-firefox) in our updated README, where installation for Firefox is described step-by-step.

Feel free to reopen this if you still get an error!

**Comment by Starty06** [comment]
Thank you so much it works perfectly now 🙏
