### ISSUE TITLE
Little issue

### ISSUE THREAD

**Issue by Starty06** [LyubomirT/c.ai-addons#13]
I'm not sure if it happens just to me but whenever I refresh the page all the memory strings I wrote are gone
Is it normal?? And is there a solution yet ?

**Comment by LyubomirT** [comment]
It is completely normal for memory strings to disappear after you refresh the page. You can try simply copy-pasting the memory string in a text file, and then clicking "Import Memory String" when back to the website. I'm currently implementing a more user-friendly approach for that though.

**Comment by Starty06** [comment]
Thank you so much 🙏🙏
Your tool has been a literal life saver
I think it's definitely too underrated
Thank you for all your hard work

**Comment by LyubomirT** [comment]
Thank you very much for these kind words, it's really pleasant for me to hear that. 🙂

I try my best to maintain this extension, and for now I promise to keep it supported for as long as possible.

In the meantime, if you want, you can spread the word so more people will find out about C.AI addons and the community of the project will grow faster.
